// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package skills

import (
	"clawunit.cuhksz/api/skills"
)

// ControllerV1 实现 api/skills.ISkillsV1 interface。
type ControllerV1 struct{}

// NewV1 返回 ControllerV1 实例，由 internal/cmd/cmd.go 在路由注册时调用。
func NewV1() skills.ISkillsV1 {
	return &ControllerV1{}
}
