// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"clawunit.cuhksz/internal/dao/internal"
)

// apiKeyProvisionsDao is the data access object for the table api_key_provisions.
// You can define custom methods on it to extend its functionality as needed.
type apiKeyProvisionsDao struct {
	*internal.ApiKeyProvisionsDao
}

var (
	// ApiKeyProvisions is a globally accessible object for table api_key_provisions operations.
	ApiKeyProvisions = apiKeyProvisionsDao{internal.NewApiKeyProvisionsDao()}
)

// Add your custom methods and functionality below.
