// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"clawunit.cuhksz/internal/dao/internal"
)

// auditEventsDao is the data access object for the table audit_events.
// You can define custom methods on it to extend its functionality as needed.
type auditEventsDao struct {
	*internal.AuditEventsDao
}

var (
	// AuditEvents is a globally accessible object for table audit_events operations.
	AuditEvents = auditEventsDao{internal.NewAuditEventsDao()}
)

// Add your custom methods and functionality below.
