// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"clawunit.cuhksz/internal/dao/internal"
)

// instancesDao is the data access object for the table instances.
// You can define custom methods on it to extend its functionality as needed.
type instancesDao struct {
	*internal.InstancesDao
}

var (
	// Instances is a globally accessible object for table instances operations.
	Instances = instancesDao{internal.NewInstancesDao()}
)

// Add your custom methods and functionality below.
