// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"clawunit.cuhksz/internal/dao/internal"
)

// userQuotasDao is the data access object for the table user_quotas.
// You can define custom methods on it to extend its functionality as needed.
type userQuotasDao struct {
	*internal.UserQuotasDao
}

var (
	// UserQuotas is a globally accessible object for table user_quotas operations.
	UserQuotas = userQuotasDao{internal.NewUserQuotasDao()}
)

// Add your custom methods and functionality below.
