// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package channels

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"

	"clawunit.cuhksz/internal/dao"
	"clawunit.cuhksz/internal/service/k8s"
	"clawunit.cuhksz/internal/service/k8s/exec"

	"github.com/gogf/gf/v2/errors/gcode"
	"github.com/gogf/gf/v2/errors/gerror"
	"github.com/gogf/gf/v2/net/ghttp"
)

// LoginSSE 是渠道扫码登录的 SSE 流式 HTTP handler。
//
// 路由 POST /api/channels/v1/login（在 internal/cmd/cmd.go 单独注册，
// 不通过 controller.Bind 绑定，因为 GoFrame controller 接口模式只能
// 一次性返回 res，无法表达流式响应）。
//
// 流程：在 Pod 内通过 K8s exec 跑 OpenClaw CLI 的 channels login 命令，
// 把它的 stdout 实时转换成 SSE data 事件推给前端 —— 二维码 ASCII art、
// 扫码状态变化都通过这个通道展示。
//
// 注意它没有挂 InjectIdentity 中间件，所以本函数自己从 ctx 取
// ownerUpn —— 同样使用 forcetypeassert 模式（提前在路由组里挂了
// InjectIdentity，所以这里只是双保险）。
func LoginSSE(r *ghttp.Request) {
	ctx := r.Context()
	ownerUpn, ok := ctx.Value("ownerUpn").(string)

	if !ok || ownerUpn == "" {
		r.Response.WriteStatus(http.StatusForbidden, "缺少用户身份")

		return
	}

	instanceID := r.Get("id").Int64()
	channel := r.Get("channel").String()

	if instanceID <= 0 || channel == "" {
		r.Response.WriteStatus(http.StatusBadRequest, "缺少 id 或 channel 参数")

		return
	}

	podName, namespace, err := getInstancePod(ctx, ownerUpn, instanceID)
	if err != nil {
		r.Response.WriteStatus(http.StatusNotFound, err.Error())

		return
	}

	// SSE headers
	r.Response.Header().Set("Content-Type", "text/event-stream")
	r.Response.Header().Set("Cache-Control", "no-cache")
	r.Response.Header().Set("Connection", "keep-alive")

	writer := r.Response.RawWriter()
	flusher, ok := writer.(http.Flusher)

	if !ok {
		r.Response.WriteStatus(http.StatusInternalServerError, "streaming not supported")

		return
	}

	// 创建 SSE writer，把 exec 输出转成 SSE 事件
	sseWriter := &sseStreamWriter{w: writer, f: flusher}

	err = exec.InPodStream(ctx, namespace, podName, "gateway", []string{
		"runuser", "-u", "node", "--",
		"node", "/app/dist/index.js", "channels", "login", "--channel", channel,
	}, sseWriter, sseWriter)
	if err != nil {
		fmt.Fprintf(writer, "event: error\ndata: %s\n\n", err.Error())
		flusher.Flush()
	}

	fmt.Fprintf(writer, "event: done\ndata: login flow ended\n\n")
	flusher.Flush()
}

// sseStreamWriter 把字节流转成 SSE data 事件
type sseStreamWriter struct {
	w io.Writer
	f http.Flusher
}

func (s *sseStreamWriter) Write(p []byte) (n int, err error) {
	for line := range strings.SplitSeq(string(p), "\n") {
		if line == "" {
			continue
		}

		// 过滤系统日志，不展示给用户
		if strings.Contains(line, "plugins.allow") ||
			strings.Contains(line, "Config overwrite") ||
			strings.Contains(line, "Config write anomaly") ||
			strings.Contains(line, "changedPaths") {
			continue
		}

		fmt.Fprintf(s.w, "data: %s\n\n", line)
	}

	s.f.Flush()

	return len(p), nil
}

// getInstancePod 获取实例的 Pod 名称和 namespace
func getInstancePod(ctx context.Context, ownerUpn string, instanceID int64) (podName, namespace string, err error) {
	record, err := dao.Instances.Ctx(ctx).
		Where("id", instanceID).
		Where("owner_upn", ownerUpn).
		One()
	if err != nil {
		return "", "", gerror.Wrapf(err, "查询实例失败")
	}

	if record.IsEmpty() {
		return "", "", gerror.NewCodef(gcode.CodeNotFound, "实例 %d 不存在", instanceID)
	}

	if record["status"].String() != "running" {
		return "", "", gerror.NewCodef(gcode.CodeNotSupported, "实例 %d 未运行", instanceID)
	}

	c := k8s.GetClient()
	namespace = c.GetUserNamespace(ownerUpn)
	podName = c.GetPodName(instanceID, record["name"].String())

	return podName, namespace, nil
}
