// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package channels

import (
	"clawunit.cuhksz/api/channels"
)

// ControllerV1 实现 api/channels.IChannelsV1 interface。
// 注意 LoginSSE 不是 interface 方法，而是同包内的独立函数。
type ControllerV1 struct{}

// NewV1 返回 ControllerV1 实例，由 internal/cmd/cmd.go 在路由注册时调用。
func NewV1() channels.IChannelsV1 {
	return &ControllerV1{}
}
