// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"clawunit.cuhksz/api/admin"
)

// ControllerV1 实现 api/admin.IAdminV1 interface。所有方法都假设上层
// 已挂载 middlewares.RequireAdmin，内部不再校验权限。
type ControllerV1 struct{}

// NewV1 返回 ControllerV1 实例，由 internal/cmd/cmd.go 在路由注册时调用。
func NewV1() admin.IAdminV1 {
	return &ControllerV1{}
}
