// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package instances

import (
	"clawunit.cuhksz/api/instances"
)

// ControllerV1 实现 api/instances.IInstancesV1 interface。
// 它没有任何字段 —— 所有依赖都从 ctx 或全局 dao/service 取得，
// 工厂模式只是为了配合 GoFrame 的路由绑定 API。
type ControllerV1 struct{}

// NewV1 返回 ControllerV1 实例，由 internal/cmd/cmd.go 在路由注册时调用。
func NewV1() instances.IInstancesV1 {
	return &ControllerV1{}
}
